name: SUSaaS CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 bandit

    - name: Lint with flake8
      run: |
        cd backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Static analysis with bandit
      run: |
        cd backend
        bandit -r . -ll

    - name: Snyk Dependency Scan
      uses: snyk/actions/python@master
      with:
        args: --file=requirements.txt --package-manager=pip
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t susaas-backend ./backend

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: susaas-backend
        format: table
        ignore-unfixed: true
        vuln-type: os,library

    - name: Run container for testing
      run: |
        docker run -d -p 8000:8000 --name susaas-test susaas-backend
        sleep 10

    - name: OWASP ZAP Baseline Scan
      run: |
        docker run --network host           -v $(pwd):/zap/wrk:rw           -t owasp/zap2docker-stable zap-baseline.py           -t http://localhost:8000/docs           -r zap-report.html           -J zap-report.json           -x zap-report.xml           -m 3

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          zap-report.html
          zap-report.json
          zap-report.xml

    - name: Stop test container
      run: docker stop susaas-test && docker rm susaas-test
