# .github/workflows/snyk.yml

name: Build and Scan with Snyk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk scan for Python dependencies
        run: snyk test --file=backend/requirements.txt --package-manager=pip --project-name=susaas-backend

      - name: Build Docker image
        run: docker build -t susaas-backend -f backend/Dockerfile backend

      - name: Snyk scan for Docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: susaas-backend
          args: --file=backend/Dockerfile --project-name=susaas-backend-container --severity-threshold=medium --exclude-base-image-vulns

      #  NEW: Snyk scan for Terraform Infrastructure-as-Code
      - name: Snyk scan for Terraform IaC
        run: snyk iac test infrastructure/ --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
